### PR TITLE
added gender pronouns as info folks should know

### PR DESCRIPTION
**Pull request by taraadiseshan**
I've really enjoyed reading through this! Thought this might be helpful for folks to ask / know as well.

### CODE REVIEW

**Comment by jessepollak** [comment]
This is a terrific change, definitely has my :+1:

**Comment by jessepollak** [comment]
Longer thought: we should also integrate this into our hiring process, so we can make sure we're treating people as they'd like to be treated from their first touch with Clef. TBH, I'm not sure what the best way to do this is, so would appreciate any guidance.

**Comment by taraadiseshan** [comment]
I'd be happy to talk more about my experience with this (preferably not on github though). And I'm sure there are other folks who'd have great advice as well. :)

**Comment by jessepollak** [comment]
Great, what's the best way to continue the conversation? You can reach me at jesse@getclef.com if email is easy!

**Pull request merged**
